<a href="https://colab.research.google.com/github/Alirs2002/comment-toxicity/blob/main/Copy_of_comment_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this project i am going to create a model to classify statements in each group based on their toxicityaa

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


first lets import our neseccary libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
import zipfile

zip_ref = zipfile.ZipFile("archive_3.zip")
! mkdir data
zip_ref.extractall("data")

now we should load our data into pandas dataframe to get a overview of the data

In [4]:
import os
data = pd.read_csv("/content/drive/MyDrive/train.csv")
data.shape

(159571, 8)

In [5]:
len(data.comment_text[:].max())

4521

In [6]:
data.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [7]:
data.tail(8)

id                                       comment_text  \
159563  ffe029a7c79dc7fe  "\nplease identify what part of BLP applies be...   
159564  ffe897e7f7182c90  Catalan independentism is the social movement ...   
159565  ffe8b9316245be30  The numbers in parentheses are the additional ...   
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
159563      0             0        0       0       0              0  
159564      0             0        0       0       0              0  
159565      0             0        0       0       0              0  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0

In [8]:
data[data.threat==1]

id                                       comment_text  \
79      003217c3eb469ba9  Hi! I am back again!\nLast warning!\nStop undo...   
176     006b94add72ed61c  I think that your a Fagget get a oife and burn...   
600     0199d6af27b715f3  I'm also a sock puppet of this account...SUPRI...   
802     02230885017a50c5  Fuck you, Smith. Please have me notified when ...   
1017    02c6e41e4b317ac3  WOULDN'T BE THE FIRST TIME BITCH. FUCK YOU I'L...   
...                  ...                                                ...   
157718  e26b106943e02cbf  bitch \nyou are a fucking hore. you suck dick ...   
158717  f264b7fb9a4b4f53  stupid head \n\nYOur dumb and you are stupid d...   
158856  f4dca9e513e0366f  Hey \n\nhey faggot, are you dead yet? or are y...   
159029  f780e4f42aa5a344                                Death to Musulmans!   
159400  fd052883fa6a8697  Shalom \n\nSemite, get the fuck out of here. I...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
79          1             0        0       1       0              0  
176         1             0        1       1       1              1  
600         1             0        0       1       0              0  
802         1             0        1       1       1              0  
1017        1             1        1       1       1              1  
...       ...           ...      ...     ...     ...            ...  
157718      1             0        1       1       1              1  
158717      1             0        1       1       1              0  
158856      1             1        1       1       1              0  
159029      1             0        0       1       0              1  
159400      1             1        1       1       1              1  

[478 rows x 8 columns]

In [9]:
len(data[data.toxic==1])

15294

In [10]:
data[data.threat==1]["comment_text"][:3]

79     Hi! I am back again!\nLast warning!\nStop undo...
176    I think that your a Fagget get a oife and burn...
600    I'm also a sock puppet of this account...SUPRI...
Name: comment_text, dtype: object

In [11]:
from tensorflow.keras.layers import TextVectorization

i define max tokents attribute as 200000

In [12]:
max_tokens = 200000

In [13]:
vectorizer = TextVectorization(max_tokens=max_tokens,
                              output_sequence_length=1800,
                               output_mode="int" )



In [14]:
X = data["comment_text"]
Y = data.iloc[:,2:]

In [15]:
Y,X

(        toxic  severe_toxic  obscene  threat  insult  identity_hate
 0           0             0        0       0       0              0
 1           0             0        0       0       0              0
 2           0             0        0       0       0              0
 3           0             0        0       0       0              0
 4           0             0        0       0       0              0
 ...       ...           ...      ...     ...     ...            ...
 159566      0             0        0       0       0              0
 159567      0             0        0       0       0              0
 159568      0             0        0       0       0              0
 159569      0             0        0       0       0              0
 159570      0             0        0       0       0              0
 
 [159571 rows x 6 columns],
 0         Explanation\nWhy the edits made under my usern...
 1         D'aww! He matches this background colour I'm s...
 2         Hey man, 

now we should adpt vectorizer to the dataset

In [16]:
print(X.values)

["Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27"
 "D'aww! He matches this background colour I'm seemingly stuck with. Thanks.  (talk) 21:51, January 11, 2016 (UTC)"
 "Hey man, I'm really not trying to edit war. It's just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. He seems to care more about the formatting than the actual info."
 ...
 'Spitzer \n\nUmm, theres no actual article for prostitution ring.  - Crunch Captain.'
 'And it looks like it was actually you who put on the speedy to have the first version deleted now that I look at it.'
 '"\nAnd ... I really don\'t think you understand.  I came here and my idea was bad right away.  What kind of community goes ""you have bad ideas"" go away, instead o

In [17]:
vectorizer.adapt(X.values)

In [18]:
vectorizer.vocabulary_size()

200000

In [19]:
vectorized_text = vectorizer(X.values)

In [20]:
type(vectorized_text)

tensorflow.python.framework.ops.EagerTensor

In [21]:
vectorized_text[2]

<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([425, 441,  70, ...,   0,   0,   0])>

In [22]:
vectorizer.get_vocabulary()

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'and',
 'a',
 'you',
 'i',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'have',
 'are',
 'your',
 'with',
 'if',
 'article',
 'was',
 'or',
 'but',
 'page',
 'my',
 'an',
 'from',
 'by',
 'do',
 'at',
 'about',
 'me',
 'so',
 'wikipedia',
 'can',
 'what',
 'there',
 'all',
 'has',
 'will',
 'talk',
 'please',
 'would',
 'its',
 'no',
 'one',
 'just',
 'like',
 'they',
 'he',
 'dont',
 'which',
 'any',
 'been',
 'should',
 'more',
 'we',
 'some',
 'other',
 'who',
 'see',
 'here',
 'also',
 'his',
 'think',
 'im',
 'because',
 'know',
 'how',
 'am',
 'people',
 'why',
 'edit',
 'articles',
 'only',
 'out',
 'up',
 'when',
 'were',
 'use',
 'then',
 'may',
 'time',
 'did',
 'them',
 'now',
 'being',
 'their',
 'than',
 'thanks',
 'even',
 'get',
 'make',
 'good',
 'had',
 'very',
 'information',
 'does',
 'could',
 'well',
 'want',
 'such',
 'sources',
 'way',
 'name',
 'these',
 'deletion',
 'pages',
 'first',
 'help'

Now I think it is time to split our dataset and preprocess our dataset

In [23]:
data_set = tf.data.Dataset.from_tensor_slices((vectorized_text,Y))
data_set = data_set.cache()
data_set = data_set.shuffle(160000)
data_set = data_set.batch(16)
data_set = data_set.prefetch(8)

In [24]:
train_data = data_set.take(int(len(data_set)*0.7))
val_data = data_set.skip(int(len(data_set)*0.7)).take(int(len(data_set)*0.2))
test_data = data_set.skip(int(len(data_set)*0.9)).take(int(len(data_set)*0.1))

In [25]:
type(train_data)

tensorflow.python.data.ops.take_op._TakeDataset

In [26]:
train_data.as_numpy_iterator().next()

(array([[ 647,    4, 1710, ...,    0,    0,    0],
        [ 797,    2,   79, ...,    0,    0,    0],
        [ 281,  376,    8, ...,    0,    0,    0],
        ...,
        [  94,    8,   44, ...,    0,    0,    0],
        [  70,   51,    6, ...,    0,    0,    0],
        [  23,   21, 1554, ...,    0,    0,    0]]),
 array([[0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]))

In [27]:
train_data.as_numpy_iterator().next()[1]

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

Now it is time to create our model

In [55]:
model1 = tf.keras.models.Sequential()
model1.add(tf.keras.layers.Embedding(max_tokens,32))
model1.add(tf.keras.layers.Conv1D(128,3,padding="valid"))
model1.add(tf.keras.layers.MaxPooling1D())
model1.add(tf.keras.layers.Conv1D(256,3,padding="valid"))
model1.add(tf.keras.layers.MaxPooling1D())
#model1.add(tf.keras.layers.Flatten())
model1.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64,activation='tanh')))
model1.add(tf.keras.layers.Dense(128,activation=tf.keras.activations.relu))
model1.add(tf.keras.layers.Dropout(0.2))
model1.add(tf.keras.layers.Dense(256,activation=tf.keras.activations.relu))
model1.add(tf.keras.layers.Dropout(0.1))
model1.add(tf.keras.layers.Dense(128,activation=tf.keras.activations.relu))
model1.add(tf.keras.layers.Dense(6,activation=tf.keras.activations.sigmoid))

In [56]:
model1.compile(loss=tf.keras.losses.BinaryCrossentropy(),
               optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
               metrics=[tf.keras.metrics.Accuracy()])

In [57]:
model1.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_9 (Embedding)     (None, None, 32)          6400000   
                                                                 
 conv1d_6 (Conv1D)           (None, None, 128)         12416     
                                                                 
 max_pooling1d_4 (MaxPoolin  (None, None, 128)         0         
 g1D)                                                            
                                                                 
 conv1d_7 (Conv1D)           (None, None, 256)         98560     
                                                                 
 max_pooling1d_5 (MaxPoolin  (None, None, 256)         0         
 g1D)                                                            
                                                                 
 bidirectional_9 (Bidirecti  (None, 128)              

In [59]:
model1.fit(train_data,
           epochs=8,
           validation_data=val_data)

Epoch 1/8
6981/6981 [==============================] - 346s 49ms/step - loss: 0.0782 - accuracy: 0.0000e+00 - val_loss: 0.0485 - val_accuracy: 0.0000e+00
Epoch 2/8
6981/6981 [==============================] - 282s 40ms/step - loss: 0.0471 - accuracy: 0.0000e+00 - val_loss: 0.0409 - val_accuracy: 0.0000e+00
Epoch 3/8
6981/6981 [==============================] - 278s 40ms/step - loss: 0.0434 - accuracy: 0.0000e+00 - val_loss: 0.0397 - val_accuracy: 0.0000e+00
Epoch 4/8
6981/6981 [==============================] - 292s 42ms/step - loss: 0.0404 - accuracy: 0.0000e+00 - val_loss: 0.0402 - val_accuracy: 0.0000e+00
Epoch 5/8
6981/6981 [==============================] - 278s 40ms/step - loss: 0.0381 - accuracy: 0.0000e+00 - val_loss: 0.0339 - val_accuracy: 0.0000e+00
Epoch 6/8
6981/6981 [==============================] - 276s 39ms/step - loss: 0.0361 - accuracy: 0.0000e+00 - val_loss: 0.0328 - val_accuracy: 0.0000e+00
Epoch 7/8
6981/6981 [==============================] - 280s 40ms/step - loss

In [60]:
test_results = model1.predict(test_data,verbose=0)

In [61]:
test_results

array([[5.3817371e-06, 7.2641878e-14, 5.6818003e-08, 4.7471023e-09,
        9.5704841e-08, 4.4448989e-10],
       [8.4800960e-04, 2.8466742e-09, 1.5093077e-05, 6.0750026e-06,
        3.2221054e-05, 1.4626938e-06],
       [1.2597308e-03, 4.1511159e-09, 1.9909054e-05, 8.3316854e-06,
        4.2989319e-05, 2.1723899e-06],
       ...,
       [3.1414133e-05, 2.3573448e-12, 4.3969834e-07, 4.4105480e-08,
        7.0210194e-07, 6.0438947e-09],
       [2.4672051e-06, 1.7267587e-14, 2.2648496e-08, 2.0180129e-09,
        4.0474543e-08, 1.6225822e-10],
       [3.6736275e-03, 1.4853984e-08, 5.5597568e-05, 1.8708930e-05,
        1.1906104e-04, 6.5487066e-06]], dtype=float32)

In [62]:
test_results.shape

(15952, 6)

In [63]:
test_results[test_results>0.5]=1
test_results[test_results<=0.5]=0

In [64]:
test_results[:16]

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)

In [65]:
test_data.as_numpy_iterator().next()[1]

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

now it is time to evaluate our model

In [66]:
from tensorflow.keras.metrics import CategoricalAccuracy
acc = CategoricalAccuracy()
for batch in test_data.as_numpy_iterator():
  x_true,y_true = batch
  y_hat = model1.predict(x_true,verbose=1)

  acc.update_state(y_true,y_hat)



1/1 [==============================] - 0s 42ms/step


In [67]:
print(acc.result().numpy())

0.99404466


the accuracy is hight because most are zero
we should measure recall and presicion

In [68]:
from tensorflow.keras.metrics import Recall,Precision

In [69]:
prec = Precision()
rec = Recall()

for batch in test_data.as_numpy_iterator():
  x_true,y_true = batch

  y_hat = model1.predict(x_true,verbose=0)
  prec.update_state(y_true,y_hat)
  rec.update_state(y_true,y_hat)

print(f"recall : {rec.result().numpy()}")
print(f"precision: {prec.result().numpy()}")

recall : 0.813540518283844
precision: 0.8679692149162292


as we can see if we had enough time to train for more epochs,it would get better results